name: Build Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install Angular Dependencies
      run: |
        cd angular
        npm install


    # Create production angular webpack build
    - name: Build Angular Production App
      run: |
        cd angular
        ng build --configuration production

    - name: Copy Files to Output Directory
      run: |
        mkdir -p output/angularProd
        cp -r angular/dist/dashboard output/angularProd/


    ## Build Go App
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.4'

    - name: Build Go App
      run: |
        cd api
        $env:GOOS="windows"; go build -o api .\main.go; $env:GOOS="linux"

    - name: Copy Files to Output Directory
      run: |
        cp api/api.exe output/
        cp api/.env-template output/


    ## Build Artifacts
    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: artifacts
        path: output/
